hideHostname: true
pathInMiddlePanel: true
disableSearch: true
showConsole: true
suppress-warnings: true
theme:
  spacing:
    unit: 5
    sectionHorizontal: 40
    sectionVertical: 40
  breakpoints:
    small: 50rem
    medium: 85rem
    large: 105rem
  colors:
    tonalOffset: 0.3
    primary:
      main: "#00B3B3"
    success:
      main: "#39BF7C"
    warning:
      main: "#FFC600"
    error:
      main: "#FF4040"
    text:
      primary: "#1B2733"
      secondary: "#1B2733"
    responses:
      success:
        color: "#F7F9FA"
        backgroundColor: "#39BF7C"
      error:
        color: "#F7F9FA"
        backgroundColor: "#FF4040"
      redirect:
        color: "#F7F9FA"
        backgroundColor: "#D4D8DB"
      info:
        color: "#F7F9FA"
        backgroundColor: "#D4D8DB"
    http:
      get: "#39BF7C"
      post: "#2483B3"
      put: "#ADCC14"
      options: "#BF73E6"
      patch: "#8257D9"
      delete: "#4D4DBF"
      basic: "#D4D8DB"
      link: "#17A1E6"
      head: "#BF73E6"
  schema:
    linesColor: "#00B3B3"
    defaultDetailsWidth: 75%
    typeNameColor: "#1B2733"
    typeTitleColor: "#1B2733"
    requireLabelColor: "#FF4040"
    labelsTextSize: 0.9em
    nestingSpacing: 1em
    nestedBackground: "#FAFBFC"
    arrow:
      size: 1.1em
      color: "#1B2733"
  typography:
    fontSize: 14px
    lineHeight: 1.5em
    fontWeightRegular: '400'
    fontWeightBold: '600'
    fontWeightLight: '300'
    fontFamily: Roboto, sans-serif
    smoothing: antialiased
    optimizeSpeed: true
    headings:
      fontFamily: Montserrat, sans-serif
      fontWeight: '400'
    code:
      fontSize: 13px
      fontFamily: Courier, monospace
      lineHeight: 1.5em
      fontWeight: '400'
      color: "#FF4040"
      backgroundColor: rgba(38, 50, 56, 0.05)
      wrap: false
    links:
      color: "#00B3B3"
      visited: "#00B3B3"
      hover: "#00B3B3"
  menu:
    width: 300px
    backgroundColor: "#031F29"
    textColor: "#F7F9FA"
    groupItems:
      textTransform: uppercase
    level1Items:
      textTransform: none
    arrow:
      size: 1.5em
      color: "#F7F9FA"
  logo:
    maxHeight: 300px
    maxWidth: 300px
  rightPanel:
    backgroundColor: "#031F29"
    width: 40%
    textColor: "#6A7C8F"
  codeSample:
    backgroundColor: "#031F29"
redocURL: https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js
